### ISSUE TITLE
Sometimes image/video/3d settings dialog opens over profile dialog

### ISSUE THREAD

**Issue by aminabs** [Utopia42-club/utopia42-unity#11]
Sometimes when I try to open the image settings dialog, the profile dialog opens behind the desired one.
Attached please find a visual description of what happens:

![photo_2022-01-29_00-06-10](https://user-images.githubusercontent.com/13463511/151617774-1fef1de3-80d5-431a-81ee-d619b1921c68.jpg)

**Comment by Navid-Fkh** [comment]
Problem is fixed... 
Will be published by the next release
