### ISSUE TITLE
A list of all player's lands would help a lot when managing/switching one's lands on the map view

### ISSUE THREAD

**Issue by aminabs** [Utopia42-club/utopia42-unity#29]
A list of all player's land would help a lot when managing/switching one's lands. 
Add a vertical box which shows a list of all lands belonging to current player
- Add a  shortkey to activate the lands list 
- For each list item, show brief information about the land
-  On click over an item, focus on the land inside the map

**Comment by Navid-Fkh** [comment]
A dialog is added for the requested feature that can be opened in map and while playing with pressing "o".
Clicking on the map icon of each row navigates the player to that land in map.

**Comment by Navid-Fkh** [comment]
Owned Lands list is now present in the side panel of map ( which can be opened via F2 )
