### ISSUE TITLE
Avatar not displaying with more than 2 people

### ISSUE THREAD

**Issue by mezamashii** [Utopia42-club/utopia42-unity#72]
On https://app.utopia42.club/game When there were more than 2 people you could not see the third person, only their name plate

![unkn332own](https://user-images.githubusercontent.com/104603161/181997153-9cd7e2ee-46fc-4b28-947c-90bdf4b91b50.png)

**Comment by rasoulMrz** [comment]
I just tested this with 4 avatars and it worked fine. Anyways, we will take a deeper look into this issue.

Here is a screenshot:
![image](https://user-images.githubusercontent.com/28677424/182013474-7d466beb-f847-473b-82d6-95f6cd20415b.png)

**Comment by mezamashii** [comment]
It looks like 2 of your avatars are default- Please try with custom ReadyPlayerMe avatars. We didn't have problems until all were were custom avatars.

**Comment by mezamashii** [comment]
I was able to see multiple avatars in last week's test. yay!
