### ISSUE TITLE
Block Collision issue

### ISSUE THREAD

**Issue by mezamashii** [Utopia42-club/utopia42-unity#73]
On the https://app.utopia42.club/game map.  One of the testers reported this block collision issue. The tester is using the EDGE browser.

![wyxir](https://user-images.githubusercontent.com/104603161/181997244-b80ee64f-6d45-4c9a-a269-abf711db005c.png)

[from User Testing July 28, 2022](https://docs.google.com/document/d/1wdCe8GZmm2djueDQTW5pYlzAsNtIRHc4Rpvijdz3KaY/edit?usp=sharing)

**Comment by rasoulMrz** [comment]
I don't think this is a bug, here is an explanation of how the system works:

1. We detect the running/walking state by user input (holding SHIFT)
2. Player tries to move toward your mouse look direction

In the reported situation, when you hold down "SHIFT" you will see the running animation. and the player tries to move toward your mouse look; but as it is facing a wall, all the force that is directed to the wall gets canceled and just a tiny force towards right or left (depends on mouse direction) remains! so you will see your player moving slowly in that direction.

With these physics in mind, I don't think that the reported observation was unexpected or a bug! if you still think that this behavior is too annoying, we can discuss it further.

**Comment by mezamashii** [comment]
Ok, I have passed this info on to the tester. Thank you.
