### ISSUE TITLE
Name Plate and Avatar issues after teleporting

### ISSUE THREAD

**Issue by mezamashii** [Utopia42-club/utopia42-unity#74]
On https://app.utopia42.club/game Strange behavior when I teleported from one person’s location to another. My Avatar disappeared from Rastko, but my nameplate remained in that place until he reloaded his game. On arriving to Marc’s location, only my nameplate arrived and moved around and my Avatar did not load for him until he reloaded the game.

[from User Testing July 28, 2022](https://docs.google.com/document/d/1wdCe8GZmm2djueDQTW5pYlzAsNtIRHc4Rpvijdz3KaY/edit?usp=sharing
![nameplate2](https://user-images.githubusercontent.com/104603161/181998123-9085f537-9c92-467a-a97f-a61fbab48d0c.png)
![nameplate](https://user-images.githubusercontent.com/104603161/181998154-43e5c2e7-450c-455b-98c4-13e16f80ca28.png)
)

**Comment by rasoulMrz** [comment]
We will fix this as soon as possible. Thanks for reportring.

**Comment by KowsarAtz** [comment]
@mezamashii 
A bug that caused a similar issue has been detected and fixed. So the problem may not be reproducible in the later release of the game; But before that, it would be great if you could reproduce the bug and provide us with the browser logs (for all three players) to have a better understanding of the issue.

**Comment by mezamashii** [comment]
My next test with these guys is on August 4. Will get back to you. :)

**Comment by mezamashii** [comment]
Sometimes name plate or avatar are slow to load, but in general working now.
