### ISSUE TITLE
Floating Animation not displaying to users

### ISSUE THREAD

**Issue by mezamashii** [Utopia42-club/utopia42-unity#75]
On https://app.utopia42.club/game Sometimes floating animation does not display to others and just shows the person in the air in the standing position.
![rastko](https://user-images.githubusercontent.com/104603161/181998739-3c5671ed-0e4b-49dd-b1a9-19877c2a592f.png)
![levitating](https://user-images.githubusercontent.com/104603161/181999804-22d576f6-c012-46e5-ae53-6ecb6720cc9c.png)
[from User Testing July 28, 2022](https://docs.google.com/document/d/1wdCe8GZmm2djueDQTW5pYlzAsNtIRHc4Rpvijdz3KaY/edit?usp=sharing)

**Comment by rasoulMrz** [comment]
Solution suggestion for @KowsarAtz : it seems that you are using `grounded` in conjunction with the player state to decide if the player is floating. It is better to ignore the `avatar.grounded` whenever the `floating` property of the user state is `true`!
