### ISSUE TITLE
User stuck in spawn

### ISSUE THREAD

**Issue by mezamashii** [Utopia42-club/utopia42-unity#76]
On https://app.utopia42.club/game One of the testers, Kyuubikku is stuck in the spawn. He spawned in that spot. Metamask is connected, but he has not added his ReadyplayerMe avatar to his profile. We tried variations on the coordinates in https://app.utopia42.club/game?position=-3267,32-4508&network=network%3D80001&contract=0x8c1006cf21f1fc892536bb67d954585e0854ae80 but he just reloads in the same spot. Of note, this is the same location I got stuck in once, but the URL with coordinates freed me. 
![kyuubikkustuck](https://user-images.githubusercontent.com/104603161/182000674-0b024b78-f060-4df3-8c9e-f4044c22722d.png)
![stuckondev](https://user-images.githubusercontent.com/104603161/182001360-2389b307-f6bd-46fc-8e87-98c256276690.png)
Amin and Rasoul had a meeting with Matt about this area freezing players due to memory issues, but Matt has not cleared out any assets.

[from User Testing July 28, 2022](https://docs.google.com/document/d/1wdCe8GZmm2djueDQTW5pYlzAsNtIRHc4Rpvijdz3KaY/edit?usp=sharing)

**Comment by rasoulMrz** [comment]
Can you provide the browser log when this error occurs? (you can access this by pressing `ctrl + shift + j` on chrome)

I will take a deeper look into matt's designs to find out which part is consuming too much memory.

**Comment by mezamashii** [comment]
Sorry, the user hasn't been available. I went and got myself stuck. :) Here is the log
[app.utopia42.club-1659459738903.log](https://github.com/Utopia42-club/utopia42-unity/files/9244298/app.utopia42.club-1659459738903.log)

**Comment by mezamashii** [comment]
I was able to get out using the URL with coordinates, but it doesn't work for Matt. He tried to go in and edit the area, but he is now stuck and the URL with coordinates doesn't move him.

**Comment by mezamashii** [comment]
Testing August 4, 2022. Kyuubikku was free on launch of the game after leaving it stuck last week and we thought it was fixed, and now tester Marc is stuck.

**Comment by mezamashii** [comment]
This has been fixed. Thank you!
