### ISSUE TITLE
Add support for modular api

### ISSUE THREAD

**Issue by aminabs** [Utopia42-club/utopia42-unity#9]
Let web developers use an api to work with 3d world.
- Consider security issues like changing others' lands using these api.

A module is a javascript code to manipulate the world using available built-in features like
- selection
- copy/paste
- marker meta-block

In a programmer point of view, consider a module as a function with some input parameters. The parameter selection is done via a dialog inside the unity scene by the player.

Each module when added to the user's module repository (e.g., free modules, paid modules) is available for the player to use:
- Need a simple ui/ux for module selection
- Need a simple page (dialog or so) for module parameter selection
- For a specific block to get selected as an input parameter, the player should already mark the block using marker meta-block
- When execution of a module is triggered, the module starts running and the player may see the execution results in realtime or after the execution ends.

As an example, consider a wall-creator module.
- Player selects the module to add to their repository
- Player selects the module for execution
- Player selects start/end coordinates which is supposed to form start/end of the wall
- Player enters an int value as the height
- Player starts executing the module
- The input parameter dialog is closed
- The module starts running, live results might be applied to the scene

**Comment by rasoulMrz** [comment]
Github api for reading a source code file:

https://api.github.com/repos/{username}/{repository_name}/contents/{file_path}

**Comment by rasoulMrz** [comment]
Steps to implement:

1. Download a js source code from github and execute it in utopia-web
2. Add basic api methods to unity UtopiaApi game object
3. Add a property to js window to call UtopiaApi methods. (outcome: window.utopiaApi.movePlayerTo(x, y, z))
4. Introduce a json structure for script definition (i.e. funciton name and parameters)
5. Add module repository to utopia-server
6. Add support for browsing the module repository, selecting a module, passing inputs, and executing
   - implement Flag meta-blocks to use as parameters
